steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_NAME}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_NAME}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - run
    - deploy
    - ${_NAME}
    - --image gcr.io/${PROJECT_ID}/${_NAME}
    - --platform managed
    - --port 8000
    - --region ${_REGION}
    - --allow-unauthenticated
images:
  - gcr.io/${PROJECT_ID}/${_NAME}
