steps:
  # Pull latest image to reuse as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/${PROJECT_ID}/${_NAME}:latest || exit 0'


  # Build container images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t=gcr.io/${PROJECT_ID}/${_NAME}:${COMMIT_SHA}'
      - '-t=gcr.io/${PROJECT_ID}/${_NAME}:latest'
      - '--cache-from=gcr.io/${PROJECT_ID}/${_NAME}:latest'
      - '.'


  # Push container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_NAME}:${COMMIT_SHA}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_NAME}:latest']


  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_NAME}'
      - '--image=gcr.io/${PROJECT_ID}/${_NAME}:${COMMIT_SHA}'
      - '--platform=managed'
      - '--port=8000'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
