# This file contains configuration properties
#  that can be overridden by environment variables.

# Which HTTP port the server should listen on
PORT: 8000

# Accepts either:
#  (string) "./serviceAccountKey.json" - using the private key in the path
#  (string) "serverless"               - for running in Google Cloud Functions
#  (string) "default"                  - using Google Application Default Credentials
GCP_FIRESTORE_AUTH: "default"

# Accepts either:
#  (string) "./serviceAccountKey.json" - using the private key in the path
#  (string) "default"                  - using Google Application Default Credentials
GCP_STORAGE_AUTH: "default"

SOCIAL_FACEBOOK_PAGE_ID: PAGE_ID_GOES_HERE
SOCIAL_FACEBOOK_PAGE_ACCESS_TOKEN: PAGE_TOKEN_GOES_HERE

DATA_STORAGE_CONTAINER: yuxel
DATA_COLLECTION_NEWS: yuxel-news