export const enum ConfigKey {
    PORT = "PORT",
    GCP_FIRESTORE_AUTH = "GCP_FIRESTORE_AUTH",
    GCP_STORAGE_AUTH = "GCP_STORAGE_AUTH",
    SOCIAL_FACEBOOK_WEBHOOK_URL = "SOCIAL_FACEBOOK_WEBHOOK_URL",
}
